unginx

diff --git a/ci/image-builder b/ci/image-builder
--- a/ci/image-builder
+++ b/ci/image-builder
@@ -14,7 +14,7 @@ fi
 
 CONTEXT="context"
 DOCKERFILE="dockerfile/Dockerfile"
-CI_LOGS=".ci/log"
+ARTIFACTS=".artifacts"
 
 if ! [[ -d ${CONTEXT} ]]
 then
@@ -80,17 +80,17 @@ for arg in ${BUILD_ARGS:-}
 do
   export $arg
   ARGS+=( "--build-arg" "${arg}" )
-done 
+done
 
 exec 101>&1 102>&2
 if [[ -z ${NOLOG:-} ]]
 then
-  if ! mkdir -p "${CI_LOGS}"
+  if ! mkdir -p "${ARTIFACTS}"
   then
-    printf -- "ERROR: Unable to create LOG directory ...\n"
+    printf -- "ERROR: Unable to create ARTIFACTS directory ...\n"
     exit 100
   fi
-  exec >"${CI_LOGS}/build-${NAME,,}.txt" 2>&1
+  exec >"${ARTIFACTS}/build-${NAME,,}.txt" 2>&1
 fi
 
 rc=0
